server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: configserver:http://localhost:8888
   
    cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant-service/**s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

      