server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
